--- 
affinity: {}
fullnameOverride: ""
imagePullSecrets: []
images: 
  jmeter_master: 
    imageName: "jmetertesfwkacr.azurecr.io/testframework/jmetermaster:latest"
  jmeter_slave: 
    imageName: "jmetertesfwkacr.azurecr.io/testframework/jmeterslave:latest"
  reporter: 
    imageName: "jmetertesfwkacr.azurecr.io/testframework/reporter:latest"
ingress: 
  annotations: {}
  enabled: false
  hosts: 
    - 
      host: chart-example.local
      paths: []
  tls: []
nameOverride: ""
#set this to specify the nodepool
nodeSelector: {
  "environment": "testpool"
}
podSecurityContext: {}
pvc: 
  grafanaDiskName: azure-grafana-disk
  influxDiskName: azure-influx-disk
  volumeAccessMode: ReadWriteOnce
  volumeSize: 10Gi
replicaCount: 1
resources: {}
securityContext: {}
service:
  azureegressip: 23.97.150.35
  jmeterinfluxdb: 
    apiPort: 8086
    graphitePort: 2003
    httpPort: 8083
    type: ClusterIP
  jmeterslaves: 
    firstPort: 1099
    label: "jmeter_mode: slave"
    secondPort: 50000
  reporter: 
    label: "app: reporter"
    port: 3000
    selector: "app: reporter"
    type: ClusterIP
serviceAccount: 
  create: true
  name: ~
tolerations: []
applicationInsightsInstrumentationKey: "4459031d-c0d4-4554-b847-89c8d7b4b861"
host: "xy.westeurope.cloudapp.azure.com"
