---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-influxdb
  labels:
    app: reporter
spec:
  ports:
    - port: {{ .Values.service.jmeterinfluxdb.apiPort }}
      name: api
      targetPort: {{ .Values.service.jmeterinfluxdb.apiPort }}
    - port: {{ .Values.service.jmeterinfluxdb.httpPort }}
      name: http
      targetPort: {{ .Values.service.jmeterinfluxdb.httpPort }}
    - port: {{ .Values.service.jmeterinfluxdb.graphitePort }}
      name: graphite
      targetPort: {{ .Values.service.jmeterinfluxdb.graphitePort }}
  selector:
    app: reporter
    
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-slaves-svc
  labels:
    jmeter_mode: slave
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.jmeterslaves.firstPort }}
      name: first
      targetPort: {{ .Values.service.jmeterslaves.firstPort }}
    - port: {{ .Values.service.jmeterslaves.secondPort }}
      name: second
      targetPort: {{ .Values.service.jmeterslaves.secondPort }}
  selector:
    jmeter_mode: slave
---
apiVersion: v1
kind: Service
metadata:
  name: reporter
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app: reporter
